name: Build and Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@saulshanabrook'
    - run: yarn install
    - run: yarn build
    - run: yarn pack -f package.tgz
    - uses: softprops/action-gh-release@v2
      with:
        files: package.tgz
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    - run: yarn install
    - run: yarn lint
